### ISSUE TITLE
How to modify dataset to .npy format

### ISSUE THREAD

**Issue by wrannaman** [cool-xuan/BN-WVAD#2]
Hi, great work, I am trying to run the model against new videos and am not able to figure out how you converted the mp4s to .npy file format. Doing it naively results in huge file sizes! 

Could you share how you're converting the XD dataset to .npy format? Thanks!

**Comment by cool-xuan** [comment]
We appreciate your acknowledgment of our work. To process raw videos into temporal features, you can utilize some video feature extractors, where I3D is widely adopted in Weakly Supervised Video Anomaly Detection (WVAD).

For our implementation, we employed the I3D project available at [this GitHub repository](https://github.com/piergiaj/pytorch-i3d). Using this tool, we generated temporal features and saved them as numpy (npy) files.

**Comment by wrannaman** [comment]
Awesome, thank you!

**Comment by AmirTarek74** [comment]
> Awesome, thank you!

did you know how to use the mentioned model ?
